# Generated by Django 6.1 on 2026-08-11 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='ubicación')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='aforo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='fin')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=20)),
                ('recurrence', models.CharField(choices=[('none', 'No recurrente'), ('daily', 'Diaria'), ('weekly', 'Semanal')], default='none', max_length=10)),
                ('recurrence_group', models.UUIDField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.resource')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día de la semana')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(verbose_name='hora de fin')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='bookings.resource')),
            ],
            options={
                'verbose_name': 'disponibilidad',
                'verbose_name_plural': 'disponibilidades',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
