# Generated by Django 6.1 on 2026-08-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='recurrence',
            field=models.CharField(choices=[('none', 'No recurrente'), ('daily', 'Diaria'), ('weekly', 'Semanal')], default='none', max_length=10, verbose_name='recurrencia'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.resource', verbose_name='recurso'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=20, verbose_name='estado'),
        ),
    ]
